#!/bin/sh -e

if [ -d 'venv/bin' ] ; then
    PREFIX="venv/bin/"
elif [ -d 'venv/Scripts' ] ; then
    PREFIX="venv/Scripts/"
else
    PREFIX=""
fi

set -x

${PREFIX}python -m build
${PREFIX}twine check dist/*
${PREFIX}mkdocs build
