#!/bin/sh -e

export PREFIX=""
if [ -d 'venv/bin' ] ; then
    export PREFIX="venv/bin/"
elif [ -d 'venv/Scripts' ] ; then
    export PREFIX="venv/Scripts/"
fi
export SOURCE_FILES="httpx tests"

set -x

./scripts/sync-version
${PREFIX}ruff format $SOURCE_FILES --diff
${PREFIX}mypy $SOURCE_FILES
${PREFIX}ruff check $SOURCE_FILES
