#!/bin/sh -e

export PREFIX=""
if [ -d 'venv/bin' ] ; then
    export PREFIX="venv/bin/"
elif [ -d 'venv/Scripts' ] ; then
    export PREFIX="venv/Scripts/"
fi
export SOURCE_FILES="httpx tests"

set -x

${PREFIX}coverage report --show-missing --skip-covered --fail-under=100
