#!/bin/sh -e

# Use the Python executable provided from the `-p` option, or a default.
[ "$1" = "-p" ] && PYTHON=$2 || PYTHON="python3"

REQUIREMENTS="requirements.txt"
VENV="venv"

set -x

if [ -z "$GITHUB_ACTIONS" ]; then
    "$PYTHON" -m venv "$VENV"
    if [ -d "$VENV/Scripts" ]; then
        PIP="$VENV/Scripts/pip"
    else
        PIP="$VENV/bin/pip"
    fi
else
    PIP="pip"
fi

"$PIP" install -U pip
"$PIP" install -r "$REQUIREMENTS"
