#!/bin/sh

export PREFIX=""
if [ -d 'venv/bin' ] ; then
    export PREFIX="venv/bin/"
elif [ -d 'venv/Scripts' ] ; then
    export PREFIX="venv/Scripts/"
fi

set -ex

if [ -z $GITHUB_ACTIONS ]; then
    scripts/check
fi

${PREFIX}coverage run -m pytest "$@"

if [ -z $GITHUB_ACTIONS ]; then
    scripts/coverage
fi
